### ISSUE TITLE
511_Assingment4_Final_Outline _Winter

### ISSUE THREAD

**Issue by sow5180** [sow5180/511_Winter_Final#1]
@rogilmore As part of assignment 4, I have created repo 511_Winter_Final and uploaded an outline of my potential project.

**Comment by rogilmore** [comment]
Fine as a skeleton. No ideas yet about what you might do?

Separately, you might try rendering the .Rmd file as an a `github_document` and then pushing it, just to get some practice with these tools.

**Comment by sow5180** [comment]
I plan to do a website for a project I am working on called Facilitating Semantic Selection in Older Adults

**Comment by rogilmore** [comment]
Great. Does the project have a website now, or will you be generating one from scratch? Also, have you thought about the components you will want to add?

**Comment by sow5180** [comment]
No, the project is brand new so no website yet. As for components I would like to include the pages on the outline (about the project, participant info etc.) as well as a workflow for the data collection. Depending on how this week's assignment goes, I think it would be neat to have simulated data on there as well.
